### ISSUE TITLE
After about an hour or two rainbow seems to hit a steady state. Is this expected?

### ISSUE THREAD

**Issue by senrabc** [Tebs-Lab/conways-game-of-life#2]
Thanks for sharing your work. Just curious. I let rainbow (https://tebs-game-of-life.com/rainbow/rainbow.html) run for a while and it appears to have hit a steady state where it appears that nothing is dying or being born. Is this expected? 
![screen shot 2018-07-17 at 10 51 36 am](https://user-images.githubusercontent.com/874070/42825278-acd259fe-89af-11e8-8667-4150d95cd547.png)

Thanks,

Chris

**Comment by tebba-von-mathenstein** [comment]
My pleasure, thanks for being curious and asking!

It is expected for rainbow (and many of the others) to reach a stable state. The upper part of this simulation is the standard Conway's rules which does have **some** infinite patterns, such as the [Gosper gun](https://tebs-game-of-life.com/gosper-gun/gosper-gun.html), but usually the system resolves to a combination of 2 state "blinkers" (such as the vertical or horizontal 3 pixel lines) or stable shapes such as the 2 by 2 boxes. 

The bottom section reaches stability (all tiles dead) much faster because the rules in that section are a a little bit "harsher". You can always click and drag to add a little asymmetry and a little more life!

If you want a really cool stable state, try loading up Conway's Editor and draw a straight line 10 pixels long. Instead of 2 states, this "pulsar" has 15 states, but still repeats infinitely. There are some other cool longish repeating patterns but the 10-line is by far the easiest to draw.

**Comment by tebba-von-mathenstein** [comment]
I'm going to close this issue, but feel free to continue commenting here and I'll respond of course :)
